apiVersion: v2
name: owncloud
description: A file sharing server that puts the control and security of your own data back into your hands.
type: application
  
version: 0.3.7
appVersion: "10.13.2"

dependencies:
- name: mariadb
  condition: mariadb.enabled
  version: "11.0.14"
  repository: "https://charts.bitnami.com/bitnami"
- name: redis
  version: "16.x.2"
  repository: "https://charts.bitnami.com/bitnami"

home: https://github.com/djjudas21/owncloud-helm
icon: https://bitnami.com/assets/stacks/owncloud/img/owncloud-stack-220x234.png
keywords:
  - owncloud
  - storage
  - http
  - web
  - php
  - dav
maintainers:
  - name: djjudas21
    email: djjudas21@users.noreply.github.com
sources:
  - https://hub.docker.com/r/owncloud/server
  - https://owncloud.org/
annotations:
  category: Infrastructure
  artifacthub.io/changes: |-
    - kind: changed
      description: Update to ownCloud 10.13.2
