apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  {{- if .Values.mariadb.enabled }}
  OWNCLOUD_DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc  }}
  {{- else }}
  OWNCLOUD_DB_PASSWORD: {{ .Values.ownCloud.externalDatabase.password | b64enc }}
  {{- end }}
  OWNCLOUD_ADMIN_PASSWORD: {{ .Values.ownCloud.adminPassword | b64enc }}
  {{- if .Values.ownCloud.mail.smtp.password }}
  OWNCLOUD_MAIL_SMTP_PASSWORD: {{ .Values.ownCloud.mail.smtp.password | b64enc }}
  {{- end }}